# Generated by Django 6.0.1 on 2026-01-18 12:16

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_categories_slug_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BigIntegerField(default=0, help_text='must be 1 or more', validators=[user.models.no_less]),
        ),
    ]
