# Generated by Django 6.0.1 on 2026-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_role_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
